version: '3'

services:
  backend:
    env_file:
      - ./server/development.env
    volumes:
      - './server:/server'
    ports:
      - 3000:3000

  frontend:
    env_file:
      - ./client/development.env
    volumes:
      - './client:/client'
    ports:
      - 3001:3001
