version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./server
    networks:
      - backend-network
    depends_on:
      - mongodb
    restart: always

  mongodb:
    container_name: mongo
    image: mongo
    networks:
      - backend-network
    volumes:
      - './db:/data/db'
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./client
    networks:
      - backend-network
    restart: always
    depends_on:
      - backend

networks:
  backend-network:
    driver: bridge
