version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./server
    networks:
      - backend-network

  mongodb:
    container_name: mongo
    image: mongo
    networks:
      - backend-network
    volumes:
      - './db:/data/db'

  frontend:
    container_name: frontend
    build:
      context: ./client
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
