export * from './Admin.page'
export * from './Home.page'
export * from './Gallery.page'
export * from './Login.page'
export * from './ContactUs.page'
export * from './WhoWeAre.page'
export * from './Portfolio.page'
